module.exports = [
    {
    "id": 1,
    "first_name": "Cicily",
    "last_name": "Assandri",
    "email": "cassandri0@upenn.edu"
  }, {
    "id": 2,
    "first_name": "Babs",
    "last_name": "Balkwill",
    "email": "bbalkwill1@slashdot.org"
  }, {
    "id": 3,
    "first_name": "Mitchel",
    "last_name": "Igounet",
    "email": "migounet2@tinypic.com"
  }, {
    "id": 4,
    "first_name": "Aubrette",
    "last_name": "Gascone",
    "email": "agascone3@ebay.com"
  }, {
    "id": 5,
    "first_name": "Brade",
    "last_name": "Stitch",
    "email": "bstitch4@redcross.org"
  }, {
    "id": 6,
    "first_name": "Pepita",
    "last_name": "Muccino",
    "email": "pmuccino5@walmart.com"
  }, {
    "id": 7,
    "first_name": "Romona",
    "last_name": "Pettengell",
    "email": "rpettengell6@cbslocal.com"
  }, {
    "id": 8,
    "first_name": "Patten",
    "last_name": "Bloodworth",
    "email": "pbloodworth7@ca.gov"
  }, {
    "id": 9,
    "first_name": "Maxine",
    "last_name": "Loughran",
    "email": "mloughran8@illinois.edu"
  }, {
    "id": 10,
    "first_name": "Ermin",
    "last_name": "Hanford",
    "email": "ehanford9@bloomberg.com"
  }, {
    "id": 11,
    "first_name": "Edi",
    "last_name": "March",
    "email": "emarcha@com.com"
  }, {
    "id": 12,
    "first_name": "Grantham",
    "last_name": "Beever",
    "email": "gbeeverb@gmpg.org"
  }];